### ISSUE TITLE
ARL, PBL is bugged

### ISSUE THREAD

**Issue by emarakis** [IvoVellekoop/wavesim#1]
Excellent work. However I tried to run the examples are given, and there are problems with nonperiodic conditions crash (ARL,PBL).
I would love it if you could fix it. 

"Index exceeds the number of array elements (128).

Error in Simulation.default_callback (line 303)
                    sroi = ax(obj.roi(:,2));

Error in Simulation/next (line 212)
                obj.callback(obj, state);

Error in WaveSimBase/run_algorithm (line 160)
                state = next(obj, state, can_terminate);

Error in Simulation/exec (line 178)
            state = run_algorithm(obj, state);

Error in pulse2d (line 36)
    E_set(:,:,f) = exec(sim, source);"

**Comment by gosnabrugge** [comment]
Hey emarakis,

Thank you for letting us know about the bug. The nonperiodic boundary conditions are fine. A bug popped up in the default callback function in the Simulation Class definition. It has been fixed now, so all the example scripts should run correctly again if you the pull the newest version of the code.

Kind regards,

gosnabrugge
